name: ${APP_NAME:-qcon-guide}
services:
  app:
    build:
      context: .
      target: builder

    command: ["serve", "--dev-addr=0.0.0.0:8080", "--livereload"]

    environment:
      - DEBUG=true
      - CI=false

    volumes:
      - ./docs:/app/docs
      - ./mkdocs.yml:/app/mkdocs.yml
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8080:8080"
